 
name: Build and push the image

on:
    push:
        branches:
            - master

jobs:
    build-publish-docker-hub:
        runs-on: ubuntu-latest
        steps:
            - uses: azure/docker-login@v1
              with:
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - uses: actions/checkout@v1
            - name: Build and Push the Image to DockerHub
              shell: bash
              run: ./build_and_push.sh
